version: 2.1

orbs:
  gcp-gcr: circleci/gcp-gcr@0.13.0

executors:
  node:
    docker:
      - image: node:14

jobs:
  build:
    executor: node
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - .
  test:
    executor: node
    steps:
      - attach_workspace:
          at: "."
      - run: npm test
  publish:
    executor: gcp-gcr/default
    steps:
      - attach_workspace:
          at: "."
      - run: echo $GCP_SERVICE_ACCOUNT > $GOOGLE_APPLICATION_CREDENTIALS
      - gcp-gcr/build-image:
          image: pandemic-tracker-api
          registry-url: eu.gcr.io
      - gcp-gcr/push-image:
          digest-path: /tmp/digest.txt
          image: pandemic-tracker-api
          registry-url: eu.gcr.io
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"
workflows:
  version: 2
  main:
    jobs:
      - build
      - test:
          requires:
            - build
      - publish:
          filters:
            branches:
              only: [main]
          requires:
            - test
